CREATE TABLE customers (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           fullname VARCHAR(255),
                           email VARCHAR(255)
);